/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main.qlsinhvien;

import Views.frmsinhvien;
import Views.DangkyView;
import Views.DanhSachDangKyView;
import Views.HockyView;
import Views.LopView;
import Views.MonView;

/**
 *
 * @author LNV
 */
public class AdminMainMenu extends javax.swing.JFrame {

    /**
     * Creates new form frmquanlisv
     */
    public AdminMainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menusinhvien = new javax.swing.JMenuItem();
        menulophoc = new javax.swing.JMenuItem();
        menumonhoc = new javax.swing.JMenuItem();
        menuhocky = new javax.swing.JMenuItem();
        menudangky = new javax.swing.JMenuItem();
        menudiem = new javax.swing.JMenuItem();
        menuhocphi = new javax.swing.JMenuItem();
        menuketquahoc = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 485, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 401, Short.MAX_VALUE)
        );

        jMenu1.setText("Quàn lý");

        menusinhvien.setText("Sinh viên");
        menusinhvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menusinhvienActionPerformed(evt);
            }
        });
        jMenu1.add(menusinhvien);

        menulophoc.setText("Lớp học");
        menulophoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menulophocActionPerformed(evt);
            }
        });
        jMenu1.add(menulophoc);

        menumonhoc.setText("Môn học");
        menumonhoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menumonhocActionPerformed(evt);
            }
        });
        jMenu1.add(menumonhoc);

        menuhocky.setText("Học kỳ");
        menuhocky.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuhockyActionPerformed(evt);
            }
        });
        jMenu1.add(menuhocky);

        menudangky.setText("Đăng ký môn học");
        menudangky.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menudangkyActionPerformed(evt);
            }
        });
        jMenu1.add(menudangky);

        menudiem.setText("Điểm");
        jMenu1.add(menudiem);

        menuhocphi.setText("Học phí");
        jMenu1.add(menuhocphi);

        menuketquahoc.setText("Kết quả học tập");
        jMenu1.add(menuketquahoc);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Tài khoản");

        jMenuItem8.setText("Quản lí tài khoản");
        jMenu2.add(jMenuItem8);

        jMenuItem9.setText("Đăng xuất");
        jMenu2.add(jMenuItem9);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menusinhvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menusinhvienActionPerformed

        this.dispose();
        frmsinhvien view = new frmsinhvien();
        view.setLocationRelativeTo(null);
        view.setVisible(true);
    }//GEN-LAST:event_menusinhvienActionPerformed

    private void menulophocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menulophocActionPerformed
        LopView view = new LopView();
        view.setLocationRelativeTo(null);
        view.setVisible(true);
    }//GEN-LAST:event_menulophocActionPerformed

    private void menumonhocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menumonhocActionPerformed
        MonView view = new MonView();
        view.setLocationRelativeTo(null);
        view.setVisible(true);
    }//GEN-LAST:event_menumonhocActionPerformed

    private void menudangkyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menudangkyActionPerformed
        DangkyView view = new DangkyView();
        view.setLocationRelativeTo(null);
        view.setVisible(true);
    }//GEN-LAST:event_menudangkyActionPerformed

    private void menuhockyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuhockyActionPerformed
        HockyView view = new HockyView();
        view.setLocationRelativeTo(null);
        view.setVisible(true);
    }//GEN-LAST:event_menuhockyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AdminMainMenu view = new AdminMainMenu();
                view.setLocationRelativeTo(null); // canh giữa màn hình
                view.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem menudangky;
    private javax.swing.JMenuItem menudiem;
    private javax.swing.JMenuItem menuhocky;
    private javax.swing.JMenuItem menuhocphi;
    private javax.swing.JMenuItem menuketquahoc;
    private javax.swing.JMenuItem menulophoc;
    private javax.swing.JMenuItem menumonhoc;
    private javax.swing.JMenuItem menusinhvien;
    // End of variables declaration//GEN-END:variables
}
